# Using `ggVennDiagram` {#using-ggVennDiagram}



```{r}
genes <- paste0("gene",1:1000)
set.seed(20210302)
gene_list <- list(A = sample(genes,100),
                  B = sample(genes,200),
                  C = sample(genes,300),
                  D = sample(genes,200))

library(ggVennDiagram)
p <- ggVennDiagram(gene_list)
```

## Changing palette

```{r}
library(ggplot2)
p + scale_fill_distiller(palette = "RdBu")
```

Some other palletes are:

```{r fig.asp=1.5}
RColorBrewer::display.brewer.all()
```



## Adding note

```{r}
p + labs(title = "Four sets Venn Diagram",
         subtitle = "generated by `ggVennDiagram`",
         caption = Sys.Date())
```

## Axis expansion

```{r}
p1 <- ggVennDiagram(gene_list, 
                    category.names = c("a very long name","short name","name","another name"))
p1
p1 + scale_x_continuous(expand = expansion(mult = .2))
```

## Show intersection values

When intersection values only have several members, `ggVennDiagram` is efficient to show the values in places.

```{r}
set.seed(0)
small_list <- lapply(sample(5:10, replace = TRUE, size = 4), function(x){
  sample(letters,x)
})

get_region_items(small_list)

p1 <- ggVennDiagram(small_list, 
                    category.names = LETTERS[1:4], 
                    show_intersect = TRUE,
                    label = NULL)
plotly::ggplotly(p1)
```


```{r eval=FALSE}
g <- ggplotGrob(p)
ng <- grid.ls(grid.force(g),print = FALSE)$name
txt <- ng[which(grepl("text",ng))]
cols <- sample(colors(),length(txt))
plots <- lapply(seq_along(txt),function(i){
  editGrob(grid.force(g),gPath(txt[i]),grep = T,
           gp=gpar(col=cols[i]))
})
cowplot::plot_grid(plotlist = plots)
```

